Create codeblocks.md
xcpcio/docs pull request #8
Opened 2022-04-21 06:33 UTC by enterdawn

Add codeblocks

2022-04-21 15:01 UTC, Dup4 commented
需要在配置文件中加一下文件地址，这样才会在页面左侧的 navbar 中生成导航栏，参考一下下面：

https://github.com/XCPCIO/XCPCIO/blob/517c5c3f405a1c531b0c0f3443ec928c1872ed64/mkdocs.yml#L263-L267

2022-04-21 15:02 UTC, Dup4 requested changes

2022-04-21 15:02 UTC, Dup4 commented on docs/software/ide/codeblocks.md
> +在Settings-Complier-Compiler settings-Compiler Flags下勾选需要的C/C++标准，也可以在Other compiler options手动添加编译参数。
```suggestion
在 Settings-Complier-Compiler settings-Compiler Flags 下勾选需要的 C/C++ 标准，也可以在 Other compiler options 手动添加编译参数。
```

中英文之间建议加上空格。

2022-04-22 02:08 UTC, enterdawn commented
> 需要在配置文件中加一下文件地址，这样才会在页面左侧的 navbar 中生成导航栏，参考一下下面：
> 
> https://github.com/XCPCIO/XCPCIO/blob/517c5c3f405a1c531b0c0f3443ec928c1872ed64/mkdocs.yml#L263-L267

已完成。抱歉，git用的不是太熟练，之前好像错误提交了一次pull request。

2022-04-22 02:09 UTC, Dup4 approved these changes

2022-04-22 02:10 UTC, Dup4 commented
thanks for your contribution.

2022-04-22 02:10 UTC, merged